export const icons = {
  success: '✔',
  error: '✘',
  warning: '⚠',
  info: 'ℹ',
  spinner: '⠋',
  spinnerFrames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'],
  arrow: {
    right: '→',
    left: '←',
    up: '↑',
    down: '↓',
  },
  bullet: '•',
  diamond: '◆',
  star: '★',
  heart: '♥',
  check: '✓',
  cross: '✗',
  dot: '●',
  emptyDot: '○',
  folder: '📁',
  file: '📄',
  gear: '⚙',
  rocket: '🚀',
  puzzle: '🧩',
  palette: '🎨',
  terminal: '💻',
  package: '📦',
} as const
